<?php
	
	return [
		'sector' => 'Sector',
		'bed' => 'Cama',
		'air' => 'Aire acondicionado',
		'vegetation' => 'Vegetación',
		'lateral_mirrors' => 'Espejos laterales cama',
		'mirrors_over_bed' => 'Espejos sobre la cama',
		'pool' => 'Piscina',
		'disco_lights' => 'Luces disco',
		'sound' => 'Sonido',
		'patio' => 'Solar / Patio',
		'tv' => 'Televisores',
		'ventiladors' => 'Ventiladores',
		'color_lingerie' => 'Color lencería',
		'lingerie' => 'Lencería',
		'natural_light' => 'Luz natural',
		'parkings' => 'Parqueaderos',
		'car_parking' => 'Parqueadero carros',
		'motorcycle_parking' => 'Parqueadero motos',
		'turco' => 'Turco',
		'jacuzzi' => 'Jacuzzi',
		'ambiance_lights' => 'Luces de ambientación',
		'restaurant' => 'Restaurante',
		'decor' => 'Decoración',
		'hab_tematic' => 'Temática Hab.',
		'love_chair' => 'Silla del amor',
		'swing_love' => 'Columpio del amor',
		'minibar' => 'Minibar',
		'pole_dance' => 'Tubo pole dancé',
		'hall' => 'Sala',
		'bar' => 'Barra / Comedor</label'
	];